import fs from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_ROOT = join(__dirname, '../../output/products');

const THEME_EMOJIS = {
  animals: '🐶 🐱 🐻 🐰 🦁 🐼',
  dinosaurs: '🦕 🦖 🥚 🌋 🌴',
  travel: '✈️ 🧳 🗺️ 🛫 🚌 🚗',
  space: '🚀 🌙 ⭐ 🪐 👩‍🚀',
  ocean: '🐠 🐙 🐳 🦀 🏖️',
  nature: '🌲 🍄 🦊 🌼 🐿️',
  vehicles: '🚗 🚌 🚦 🚙 🛻',
  trucks: '🚚 ⛽ 🛣️ 🧰 🛞',
  adventure: '🧭 🗺️ 🏕️ 🔎 🌄'
};

function ensureDir(dir) { fs.mkdirSync(dir, { recursive: true }); }
function safe(text) { return String(text ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

function buildPagePlan(sku, family) {
  const base = [
    { type: 'cover', title: sku.title, instructions: 'Use as the main printable cover page.' },
    { type: 'instructions', title: 'How to use this pack', instructions: `Print the pages that match your ${family.useCase} moment. Bring pencils or crayons.` },
    { type: 'find-and-circle', title: `${family.useCase} find and circle`, instructions: `Circle the ${sku.theme} items you can spot.` },
    { type: 'draw-and-tell', title: 'Draw and tell', instructions: `Draw your favorite ${family.useCase} moment and tell someone about it.` },
    { type: 'count-and-color', title: 'Count and color', instructions: `Count the themed items and color the matching number.` },
    { type: 'mini-game', title: `${family.useCase} mini game`, instructions: `Play a simple quiet-time game for this setting.` },
  ];
  if (sku.formatType.includes('journal')) {
    base.push({ type: 'memory-page', title: 'Trip memory page', instructions: 'Write or draw what you saw, ate, or loved most.' });
  }
  if (family.useCase.includes('road trip') || family.useCase.includes('scavenger')) {
    base.push({ type: 'scavenger', title: 'Scavenger hunt', instructions: 'Check off what you find on the road.' });
  }
  if (family.useCase.includes('airport') || family.useCase.includes('airplane')) {
    base.push({ type: 'bingo', title: 'Travel bingo', instructions: 'Mark each thing when you spot it.' });
  }
  return base;
}

function buildListingCopy(sku, family, pagePlan) {
  return `# ${sku.title}\n\n## Positioning\nA screen-free printable ${family.useCase} activity pack for ages ${sku.ageBand}.\n\n## Promise\nHelp parents buy 20-60 minutes of calm during ${family.useCase} time.\n\n## Included\n${pagePlan.map((page, i) => `- Page ${i + 1}: ${page.title}`).join('\n')}\n\n## Etsy title draft\n${sku.title} | ${family.useCase} printable for kids | ${sku.theme} theme\n\n## Etsy bullets\n- Instant printable activity pack\n- Designed for ages ${sku.ageBand}\n- Great for ${family.useCase} time\n- Screen-free quiet activity\n- Theme: ${sku.theme}\n\n## Notes\nThis is a real build artifact generated by the repo. It is not a live marketplace listing.`;
}

function buildHtml(sku, family, pagePlan) {
  const themeEmoji = THEME_EMOJIS[sku.theme] || '⭐ 🎨 🧩';
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${safe(sku.title)}</title>
<style>
  body{font-family:Arial,sans-serif;color:#18325f;background:#fff;margin:0}
  .page{width:8.5in;min-height:11in;padding:.55in;box-sizing:border-box;page-break-after:always}
  .cover{background:#fff9f0}
  h1{font-size:32px;margin:0 0 10px 0}
  h2{font-size:22px;margin:0 0 10px 0}
  .sub{font-size:18px;color:#5d6781;margin-bottom:18px}
  .band{display:inline-block;background:#a56cc1;color:white;padding:8px 14px;border-radius:999px;font-weight:bold;margin:8px 0}
  .box{border:2px solid #f1dfcf;border-radius:18px;padding:16px;margin:16px 0}
  .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}
  .cell{border:2px dashed #d8c7b6;border-radius:14px;padding:12px;min-height:86px}
  .emoji{font-size:28px;line-height:1.6}
  .line{border-bottom:2px solid #d8c7b6;height:28px;margin-bottom:10px}
  ul{padding-left:20px}
</style>
</head>
<body>
  <section class="page cover">
    <div class="band">Busy Little Happy</div>
    <h1>${safe(sku.title)}</h1>
    <div class="sub">${safe(sku.subtitle)}</div>
    <div class="box"><strong>Use case:</strong> ${safe(family.useCase)}<br/><strong>Age band:</strong> ${safe(sku.ageBand)}<br/><strong>Theme:</strong> ${safe(sku.theme)}<br/><strong>Format:</strong> ${safe(sku.formatType)}</div>
    <div class="box"><strong>Pack goal:</strong> give parents a printable, screen-free activity set they can actually use during ${safe(family.useCase)} time.</div>
  </section>
  <section class="page"><h2>How to use this pack</h2><ul><li>Print the pages you need.</li><li>Bring pencils, crayons, or a pen.</li><li>Use one page at a time to stretch the activity window.</li><li>Swap in fresh pages for longer travel or waits.</li></ul></section>
  ${pagePlan.slice(2).map((page) => {
    if (page.type === 'find-and-circle') return `<section class="page"><h2>${safe(page.title)}</h2><p>${safe(page.instructions)}</p><div class="grid">${Array.from({length:9}).map(()=>`<div class="cell"><div class="emoji">${safe(themeEmoji)}</div>Circle 3 favorites</div>`).join('')}</div></section>`;
    if (page.type === 'draw-and-tell') return `<section class="page"><h2>${safe(page.title)}</h2><p>${safe(page.instructions)}</p><div class="box" style="height:280px"></div><div class="line"></div><div class="line"></div><div class="line"></div></section>`;
    if (page.type === 'count-and-color') return `<section class="page"><h2>${safe(page.title)}</h2><p>${safe(page.instructions)}</p><div class="grid">${[1,2,3,4,5,6].map((n)=>`<div class="cell"><strong>${n}</strong><div class="emoji">${safe(themeEmoji)}</div>Color ${n} items</div>`).join('')}</div></section>`;
    if (page.type === 'scavenger') return `<section class="page"><h2>${safe(page.title)}</h2><p>${safe(page.instructions)}</p><ul>${['Something red','A sign','A truck or bus','A tree','A funny shape','Something from your theme'].map((item)=>`<li>${item}</li>`).join('')}</ul></section>`;
    if (page.type === 'bingo') return `<section class="page"><h2>${safe(page.title)}</h2><p>${safe(page.instructions)}</p><div class="grid">${Array.from({length:9}).map((_,i)=>`<div class="cell">Bingo square ${i+1}</div>`).join('')}</div></section>`;
    if (page.type === 'memory-page') return `<section class="page"><h2>${safe(page.title)}</h2><p>${safe(page.instructions)}</p><div class="line"></div><div class="line"></div><div class="line"></div><div class="box" style="height:220px">Draw here</div></section>`;
    return `<section class="page"><h2>${safe(page.title)}</h2><p>${safe(page.instructions)}</p><div class="box">Use this page for a quiet-time ${safe(family.useCase)} activity.</div></section>`;
  }).join('')}
</body>
</html>`;
}

export function buildSkuProductPackage(sku, family) {
  const dir = join(OUTPUT_ROOT, sku.id);
  ensureDir(dir);
  const pagePlan = buildPagePlan(sku, family);
  const html = buildHtml(sku, family, pagePlan);
  const listingCopy = buildListingCopy(sku, family, pagePlan);
  const manifest = {
    skuId: sku.id,
    title: sku.title,
    familyId: family.id,
    familyTitle: family.title,
    outputDir: dir,
    files: ['activity-pack.html', 'activity-plan.json', 'listing-copy.md', 'manifest.json'],
    builtAt: new Date().toISOString(),
    status: 'draft_artifacts_generated'
  };
  fs.writeFileSync(join(dir, 'activity-pack.html'), html, 'utf8');
  fs.writeFileSync(join(dir, 'activity-plan.json'), JSON.stringify(pagePlan, null, 2), 'utf8');
  fs.writeFileSync(join(dir, 'listing-copy.md'), listingCopy, 'utf8');
  fs.writeFileSync(join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');
  return { dir, manifest };
}

export function buildAllProductPackages(skus, families) {
  ensureDir(OUTPUT_ROOT);
  const familyMap = Object.fromEntries(families.map((family) => [family.id, family]));
  const built = [];
  for (const sku of skus) {
    built.push(buildSkuProductPackage(sku, familyMap[sku.productFamilyId]));
  }
  fs.writeFileSync(join(OUTPUT_ROOT, 'catalog-manifest.json'), JSON.stringify({ builtAt: new Date().toISOString(), count: built.length, items: built.map((b) => b.manifest) }, null, 2), 'utf8');
  return built;
}

export function getBuildStatusForSku(skuId) {
  const dir = join(OUTPUT_ROOT, skuId);
  const manifestPath = join(dir, 'manifest.json');
  if (!fs.existsSync(manifestPath)) return null;
  try { return JSON.parse(fs.readFileSync(manifestPath, 'utf8')); } catch { return null; }
}
